SELECT * FROM practica2.HABITACION;
SELECT COUNT(*) FROM practica2.HABITACION;
SELECT * FROM practica2.PACIENTE;
SELECT COUNT(*) FROM practica2.PACIENTE;
SELECT * FROM practica2.LOG_ACTIVIDAD;
SELECT COUNT(*) FROM practica2.LOG_ACTIVIDAD;
SELECT * FROM practica2.LOG_HABITACION;
SELECT COUNT(*) FROM practica2.LOG_HABITACION;